version: "3"

services:
  db:
    image: postgres:15.4
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_DB: ${NAME_DB}
    container_name: ${NAME_DB}
    volumes:
      - ./postgres-db:/var/lib/postgresql/data